Create LICENCE
IUS-CS/c346-fa23-project-mentats pull request #3
Opened 2023-09-07 15:38 UTC by Primeeight

2023-09-07 19:10 UTC, TylerPopson requested changes
The name of the app is wrong and should be Statego, not Stratego

2023-09-07 19:10 UTC, TylerPopson commented on LICENCE
> +Copyright (c) [2023] [Stratego]
The name is Statego, unfortunately we do not have the copyright to the game Stratego

2023-09-08 16:55 UTC, Primeeight commented
Fixed App Name

2023-09-08 17:21 UTC, TylerPopson approved these changes
Looks good

2023-09-08 21:06 UTC, merged

2023-09-09 17:34 UTC, snappernapper07 commented
Hey I noticed that LICENSE is misspelled, and I know Sexton said that the file names really mattered. So if you could just fix this real quick, I think it would be for the best. Thanks!